### ISSUE TITLE
Handle ESRCH error

### ISSUE THREAD

**Issue by danielfalk** [mdlawson/piping#10] opened 2015-12-31 18:12 UTC
I believe this may be a windows-only problem, but process.kill() seems to (unpredictably) throw an error.  The exact same stack trace that I get can be found in this report: https://github.com/erikras/react-redux-universal-hot-example/issues/638

ESRCH apparently means "No such process", so I'm wondering if the worker process dies before `process.kill()` is called?  If so, it's even worse that the worker processes are being killed in this way as opposed to using `worker.kill()`, since there's a slight chance that the PID could have been reused.

**Comment by Silviu-Marian** [comment] 2016-01-24 21:16
I'm seeing the same issue here.

**Comment by mntnoe** [comment] 2016-01-25 04:10
The problem is likely the [fix](https://github.com/mdlawson/piping/commit/6e552d282e715596d64f7af22469b45807e84d91) I made to solve an issue with `hapi` not exiting correctly when running with piping. The problem was that `process.on()` handlers were never fired using `worker.kill()`. I have filed a [bug report](https://github.com/nodejs/node/issues/4852).

Does the problem go away if you use this branch?

https://github.com/mntnoe/piping/tree/revert-sigterm-fix

**Comment by mntnoe** [comment] 2016-01-25 11:43
So it seems that the worker exited before it could be killed from the master. I have made an [attempt](https://github.com/mntnoe/piping/tree/sigterm-fix-2) at solving the cleanup problem using worker.kill(). I'm unsure if it handles race conditions well enough though. Can you test and see if it solves your problem?

**Comment by Silviu-Marian** [comment] 2016-01-25 19:20
Looks good so far. Thank you for the quick fix.

**Comment by danielfalk** [comment] 2016-01-25 19:27
I've tried the branch and so far, so good.  I think it's fixed.  Thank you.

**Comment by jjpatel361** [comment] 2016-04-27 19:30
Hi **@mntoe** , any chances of merging this to master and releasing on **npm** ?

**Comment by mntnoe** [comment] 2016-04-27 19:44
@mdlawson can you merge this?

**Comment by mdlawson** [comment] 2016-04-30 11:25
Merged and released as 0.3.1. Sorry for the delay!

**Closed by mdlawson** 2016-04-30 11:25 UTC
